classDiagram

class App {
    +Flask app
    +secret_key: str
    +run()
}

class Usuario {
    +id: int
    +username: str
    +password: str
    +nombre: str
}

class Imagen {
    +id: int
    +titulo: str
    +descripcion: str
    +ruta_imagen: str
    +fecha_subida: date
    +usuario_id: int
}

class DBConnection {
    +get_db_connection(): Connection
}

class AuthController {
    +login()
    +logout()
    +register()
}

class HomeController {
    +home()
    +api_imagenes()
}

App --> AuthController
App --> HomeController
AuthController --> Usuario
HomeController --> Usuario
HomeController --> Imagen
App --> DBConnection
