flowchart TD;
    A["Inici - Benvinguda"] --> B["Login"];
    B -->|Registrar usuari| C["Registre"];
    C --> E["Pantalla principal"];
    B -->|Credencials correctes| D["Login OK "];

    
    D --> E["Pantalla principal"];
    E -->|Configuració| G["Pantalla de Configuració"];
    E -->|Perfil| F["Pantalla de Perfil"];
    F -->|Modificar dades|L["Editar perfil"];
    E -->|Lista|J["Lista de nens"];
    J -->|Nen seleccionat|K["Hores actives del pegat"];
    
    B -->|He oblidat la contrasenya| H["Recuperar Contrasenya"];
    H -->|Email vàlid| I["Ingresar nova contrasenya"] --> B;
    H -->|Error| H1["Intentar de nou"] --> H;
